config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # default route / home page
  root to: 'pages#home'

  # user routes
  # get 'signin', to: 'pages#signin', as: :signin
  # get 'signup', to: 'pages#signup', as: :signup
  # post 'signup', to: 'users#create'
  # get 'profile', to: 'pages#profile'

  # Product routes

  # Product_reviews routes
  # get 'products/:id/reviews', to: 'reviews#index', as: :product_reviews
  # get 'products/:id/reviews/new', to: 'reviews#new', as: :new_product_review
  # post 'products/:id/reviews/new', to: 'reviews#create'
  # get 'products/:id/reviews/:id', to: 'reviews#show', as: :product_review

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :products, only: %i[index show]
  # resources :users, only: %i[show create new] do
  #  resources :products, only: %i[index create new show edit update]
  #   member do
  #     resources :bookings, only: %i[index show create new]
  #     resources :reviews, only: %i[show create new]
  # end
  resources :products do
    collection do
      get :sets
      get :plates
      get :cutleries
      get :glasses
    end
    resources :bookings, only: %i[new create]
    resources :reviews, only: %i[new create]
  end
  resources :reviews, only: [:destroy]
end

app/views/shared/_card.html.erb
<div class="container">
  <div class="card" style="width: 18rem;">
    <img src="/assets/dinner set.png" class="card-img-top" alt="crystal glass">
      <div class="card-body">
        <h2>Card title</h2>
        <p>Lorem ipsim dolor sit amet consectetur adipisicing elit. Magni aliquid sapiente, obcaecati dolore rerum, facilis.</p>
      </div>
      <div class="card-buttons">
        <%= link_to "Update", "#", class: "btn btn-custom" %>
        <%= link_to "Delete", "#", class: "btn btn-custom" %>
      </div>
  </div>
</div>

app/views/shared/_carousel.html.erb
<!-- Carousel -->
<div id="demo" class="carousel slide" data-bs-ride="carousel">

  <!-- Indicators/dots -->
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
    <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
    <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
  </div>

  <!-- The slideshow/carousel -->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag("banner_01.jpg", alt: "festive seasons", class: "d-block w-100") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("banner_02.jpg", alt: "fork", class: "d-block w-100") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("banner_03.jpg", alt: "glass", class: "d-block w-100") %>
    </div>
  </div>

  <!-- Left and right controls/icons -->
  <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
    <span class="carousel-control-next-icon"></span>
  </button>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center text-white" style="background-color: #BFB9AD;">
  <div class="text-center text-dark p-3" style="background-color: rgba(191, 185, 173);">
    © 2022 Copyright: &agrave table company Ltd
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <nav>
    <ul>
      <li> <%= link_to root_path do %>
        <%= image_tag "atable-logo-white.svg", class: "home-logo", alt:"home" %>
      <% end %>

      <li rel="tooltip" title="show all products"> <%= link_to products_path do %>
        <%= image_tag "atable-icon-all.svg", class: "navbar-icon", alt:"set" %>
      <% end %>

      <li rel="tooltip" title="show all sets"> <%= link_to sets_products_path do %>
        <%= image_tag "atable-icon-set.svg", class: "navbar-icon", alt:"set" %>
      <% end %>

      <li rel="tooltip" title="show all plates"> <%= link_to plates_products_path do %>
        <%= image_tag "atable-icon-plate.svg", class: "navbar-icon", alt:"plates" %>
      <% end %>

      <li rel="tooltip" title="show all cutleries"> <%= link_to cutleries_products_path do %>
        <%= image_tag "atable-icon-fork.svg", class: "navbar-icon", alt:"forks" %>
      <% end %>

      <li rel="tooltip" title="show all glasses">
      <%= link_to glasses_products_path do %>
        <%= image_tag("atable-icon-glass.svg", class: "navbar-icon", alt:"glasses") %>
      <% end %>
    </ul>
  </nav>

  <div class = "sign-in">
    <% if user_signed_in? %>
      <%= link_to new_product_path do %>
        <%= image_tag("atable-icon-upload.svg", class: "upload-icon", alt:"upload") %>
      <% end %>
      <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-sign-in" %>


    <% else %>
      <%= button_to "Sign in", new_user_session_path, class: "btn btn-sign-in " %>
    <% end %>
  </div>
</div>