config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # default route / home page
  root to: 'pages#home'

  # user routes
  # get 'signin', to: 'pages#signin', as: :signin
  # get 'signup', to: 'pages#signup', as: :signup
  # post 'signup', to: 'users#create'
  # get 'profile', to: 'pages#profile'

  # Product routes

  # Product_reviews routes
  # get 'products/:id/reviews', to: 'reviews#index', as: :product_reviews
  # get 'products/:id/reviews/new', to: 'reviews#new', as: :new_product_review
  # post 'products/:id/reviews/new', to: 'reviews#create'
  # get 'products/:id/reviews/:id', to: 'reviews#show', as: :product_review

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :products, only: %i[index show]
  # resources :users, only: %i[show create new] do
  #  resources :products, only: %i[index create new show edit update]
  #   member do
  #     resources :bookings, only: %i[index show create new]
  #     resources :reviews, only: %i[show create new]
  # end
  resources :products do
    collection do
      get :sets
      get :plates
      get :cutleries
      get :glasses
    end
    resources :bookings, only: %i[new create]
    resources :reviews, only: %i[new create]
  end
  resources :reviews, only: [:destroy]
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # Hack thanks to Cloudinary
  has_one_attached :photo

  # Added validations - don't hesitate to modify/correct it :)
  validates :name, presence: true, uniqueness: true
  validates :event_type, presence: true
  validates :product_type, inclusion: { in: %w[sets plates glasses cutleries],
    message: "%{value} is not a valid cutlery type" }
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { greater_than: 0 }

  scope :sets, -> { where(product_type: "sets") }
  scope :plates, -> { where(product_type: "plates") }
  scope :cutleries, -> { where(product_type: "cutleries") }
  scope :glasses, -> { where(product_type: "glasses") }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
  end

  def sets
    @products = Product.sets
    render :index
  end

  def plates
    @products = Product.plates
    render :index
  end

  def cutleries
    @products = Product.cutleries
    render :index
  end

  def glasses
    @products = Product.glasses
    render :index
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @review = Review.new
    @booking = Booking.new
  end

  def edit; end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :quantity, :event_type, :product_type, :photo)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/views/products/_form.html.erb
<div class="form-container">
  <div class="simple-form">
      <%= simple_form_for(@product) do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :event_type %>
        <%= f.input :product_type %>
        <%= f.input :price %>
        <%= f.input :quantity %>
        <%= f.input :photo, as: :file, input_html: {multiple: true} %>
        <%= f.button :submit , class: "btn btn-custom " %>
      <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<div class="container card rounded-3 mt-4 " style="width: 600px">
  <div class="form p-3">
    <%=  render "form", products: @products %>
  </div>
</div>

app/views/products/index.html.erb
<div>
  <%= image_tag("products-top.jpg", class: "product-image-top", alt: "top-pic" ) %>
</div>
    <h1 class="product-headline">All our beautiful Products </h1>

  <div class="row">
    <% @products.each do |product| %>
        <div class="col-md-4">
          <div class="card" style="width: 18rem;">
            <div class="img">
              <%= cl_image_tag product.photo.key, height: 300, width: 400, crop: :fill %>
            </div>
            <div class="card-body">
              <h2><%= product.name %></h2>
              <p><%= product.description.truncate_words(7) %></p>
            </div>
            <div class="card-buttons">
              <%= link_to "More info", product_path(product), class: "btn btn-green" %>
              <% if current_user %>
                <%= link_to "Book", new_product_booking_path(product),  class: "btn btn-green" %>
              <% end %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container card rounded- mt-43 " style="width: 600px">
  <div class="row">
    <div class="col">
      <div class="form p-3">
        <%=  render "form", products: @products %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="body">
  <div class="row">
      <div class="col-8">
        <div class="card">
        <div class="img">
          <%= cl_image_tag @product.photo.key, height: 300, width: 400, crop: :fill %>
        </div>
          <h1><%= @product.name %></h1>
        </div>
          <p>Description : <%= @product.description %></p>
          <p>Price : <%= @product.price %></p>
          <p>Quantity available : <%= @product.quantity %></p>
          <p>Owner of product : <%= User.find(@product.user_id).name %></p>
          <p><%= @product.name %> is currently <%= @product.is_booked ? "booked" : "not booked" %></p>
        <div class="list-group">
          <h2><%= pluralize @product.reviews.size, "review" %> on <%=@product.name%></h2>
          <% if @product.reviews.blank? %>
            Be the first to leave a review for <%= @product.name %>
          <% else %>
              <% @product.reviews.each do |review| %>
                  <li class="list-review">
                    <small>
                      <% count = 0 %>
                      <% 5.times do %>
                        <% if review.rating > count %>
                          <i class="fas fa-star star-yellow"></i>
                        <% else %>
                          <i class="far fa-star"></i>
                        <% end %>
                        <% count += 1 %>
                      <% end %>
                    </small>
                    <p><%= review.comment %></p>
                  </li>
              <% end %>
          <% end %>
        </div>
        <div class="card-buttons">
            <%= link_to "Update", edit_product_path(@product), class: "btn btn-green" %>
            <% if current_user  %>
              <%= link_to "Book", new_product_booking_path(@product), class: "btn btn-green" %>
              <%= link_to "Leave a review", new_product_review_path(@product), class: "btn btn-green" %>
            <% end %>
            <%= link_to "Delete", product_path(@product), method: :delete, remote: true, data: { confirm: 'Are you sure?' },  class: "btn btn-green" %>
        </div>
      </div>
</div>